### ISSUE TITLE
Semicolon position fixation issue 

### ISSUE THREAD

**Issue by easyhooon** [darkokoa/compose-datetime-wheel-picker#19]
https://github.com/commandiron/WheelPickerCompose/issues/43

This is an issue that existed in the previous WheelPickerCompose library, but it's still occurring in the TimePicker. I was wondering if you could help solve this problem 

![image](https://github.com/user-attachments/assets/d4e49cf8-d39e-49b9-9bfa-600866a56786)

WheelTimPicker code in project
```kotlin 
              WheelTimePicker(
                  modifier = Modifier
                      .fillMaxWidth()
                      .padding(horizontal = 15.dp),
                  startTime = uiState.mateRecruitTime.parseToLocalTime(),
                  minTime = Clock.System.now().toLocalDateTime(TimeZone.of("Asia/Seoul")).time,
                  maxTime = kotlinx.datetime.LocalTime(23, 59),
                  timeFormat = TimeFormat.AM_PM,
                  rowCount = 5,
                  textStyle = Large20_Mid,
                  textColor = Gray001,
                  selectorProperties = WheelPickerDefaults.selectorProperties(
                      enabled = true,
                      shape = RoundedCornerShape(10.dp),
                      color = Gray010,
                      border = BorderStroke(2.dp, Gray010),
                  ),
              ) { snappedTime -> run { selectedTime = snappedTime.formatToTime() } }
```

thx for reading :)

**Comment by darkokoa** [comment]
Thanks for catching this bug. I really appreciate you taking the time to report it. I'm planning to dive in and fix it soon. 

But until then, here's a quick workaround you could try: avoid using Modifier.fillMaxWidth() for now. There are plenty of other ways to center stuff in layouts that should sidestep this issue. Hope this temp fix helps you out while I work on squashing the bug for good. And your feedback is helpful in making this project better!

**Comment by easyhooon** [comment]
![image](https://github.com/user-attachments/assets/7baa932f-96cb-46f5-8b1e-da9dff240b9e)


As you mentioned, I confirmed that the position of ":" was correctly placed when I removed the `fillMaxWidth()` option from the Modifier. However, it doesn't seem to be vertically centered. Thank you for your quick feedback. I'm looking forward to the updated version :)

**Comment by darkokoa** [comment]
You can try v1.0.1 now
